### ISSUE TITLE
Current screenshots are obsolete

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/plugin-ClassicFontTheme#1]
Hi guys,
The screenshot shown is still the one the old Piwik visual identity.
There is just a new screenshot to perform and this ticket is closed.
Hope that helps,

**Comment by Stan-vw** [comment]
Thanks for the ticket. I might be missing some standard knowledge here, where exactly are we talking about?

**Comment by snake14** [comment]
Thank you @Chardonneaur . @Stan-vw It looks like [the screenshot included with the plugin](https://github.com/matomo-org/plugin-ClassicFontTheme/blob/5.x-dev/screenshots/Theme.png) hasn't been updated in about 7 years.

**Comment by Stan-vw** [comment]
Thanks @snake14 , yeah that seems pretty outdated. Can you hotfix that or should we plan it into a sprint?

**Comment by snake14** [comment]
@Stan-vw I would just hotfix it, but I don't think I have a good environment to demo the ClassicFontTheme.

**Comment by Stan-vw** [comment]
@AltamashShaikh might have this?

**Comment by Chardonneaur** [comment]
Well, in fact, that's the same as https://demo.matomo.cloud, classic theme.

**Comment by AltamashShaikh** [comment]
@Stan-vw will deploy it on some instance with reasonable data and update the screenshot, I am checking this with Cloud team.

**Comment by AltamashShaikh** [comment]
@Chardonneaur Thanks for pointing out the issue, we have updated the screenshot.
